# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: MQTT
    orgId: 1

datasources:
  - name: MQTT
    type: grafana-mqtt-datasource
    uid: jgHNXr_Vz
    jsonData:
      uri: 'tcp://broker.hivemq.com:1883'
    version: 1
    editable: true
